Improved script.

diff --git a/run-test b/run-test
--- a/run-test
+++ b/run-test
@@ -31,10 +31,17 @@
 PROGRAM="$0"
 function usage()
 {
-   echo >&2 "Usage: ${PROGRAM} NS [NS ...]"
+   echo >&2 "Usage: ${PROGRAM} NS[-parameter] [NS[-parameter] ...]"
    echo >&2 ""
-   echo >&2 "Available NSs in this directory:"
-   git ls-files | cut -d/ -f1 | sort -u | grep "_nsd$" | sed -e "s/_nsd$//g" -e "s/^/* /g" >&2
+   echo >&2 "Available NSs/parameter files in this directory:"
+   allNSs=`git ls-files | cut -d/ -f1 | sort -u | grep "_nsd$" | sed -e "s/_nsd$//g"`
+   for ns in ${allNSs} ; do
+      echo >&2 "* NS ${ns}:"
+      parameterFiles=`ls ${ns}*-params.yaml | xargs -n1 | sed -e "s/-params.yaml$//g"`
+      for parameterFile in ${parameterFiles} ; do
+         echo >&2 "  - ${parameterFile}"
+      done
+   done
 }
 
 
@@ -45,16 +52,25 @@ if [ $# -lt 1 ] ; then
 fi
 n=0
 while [ $# -gt 0 ] ; do
-   NS="$1"
-   VNFD="${NS}_vnfd"
-   NSD="${NS}_nsd"
-   PARAMS="${NS}-params.yaml"
-   if [ ! -d "${NSD}" ] ; then
-      echo >&2 "ERROR: NSD ${NSD} not found!"
-      echo >&2 ""
+   PARAMS="$1-params.yaml"
+   if [ ! -e "${PARAMS}" ] ; then
+      echo >&2 "ERROR: Parameter file ${PARAMS} not found!"
       usage
       exit 1
    fi
+   NS=`echo "${PARAMS}" | sed -e "s/-params.yaml$//g"`
+   if [ ! -d "${NS}_nsd" ] ; then
+      NS=`echo "${NS}" | sed -e "s/-[a-zA-Z0-9]*$//g"`
+      if [ ! -d "${NS}_nsd" ] ; then
+        echo >&2 "ERROR: NSD ${NS}_nsd not found!"
+        usage
+        exit 1
+     fi
+   fi
+   VNFD="${NS}_vnfd"
+   NSD="${NS}_nsd"
+
+   echo "NS=$NS NSD=$NSD VNFD=$VNFD PARAMS=$PARAMS"
 
 
    # ====== Build ===========================================================
