Improved scripts and configurations.

diff --git a/images/tmp/make-vm b/images/tmp/make-vm
--- a/images/tmp/make-vm
+++ b/images/tmp/make-vm
@@ -1,4 +1,25 @@
-#!/bin/bash -e
+#!/usr/bin/env bash
+#
+# Template VM Image Builder
+# Copyright (C) 2017-2020 by Thomas Dreibholz
+#
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#
+# Contact: dreibh@simula.no
+
+set -e
+
 
 # ###### Defaults ###########################################################
 PROJECT="Template"
@@ -60,7 +81,7 @@ while [ $# -gt 0 ] ; do
       echo >&2 "ERROR: Usage: $0"
       echo >&2 "   [--hypervisor|-H VirtualBox|QEMU]"
       echo >&2 "   [--project|-P Template|NEAT|MELODIC|...]"
-      echo >&2 "   [--destination|-D Ubuntu|Fedora]"
+      echo >&2 "   [--destination|-D Ubuntu|Fedora|FreeBSD]"
       echo >&2 "   [--release|-R RELEASE]"
       echo >&2 "   [--root|-r MiB]"
       echo >&2 "   [--home|-h MiB]"
@@ -96,6 +117,7 @@ fi
 if [ "${DISTRIBUTION}" == "Ubuntu" ] ; then
    BUILDER_INSTALL="ubuntu-${RELEASE}"
    NAME="${NAME}-Ubuntu-${RELEASE}"
+   HTTP_DIRECTORY="http/ubuntu"
    if [[ "${RELEASE}" =~ ^([0-9]*).([0-9]*)$ ]] ; then
       y=${BASH_REMATCH[1]}
       m=${BASH_REMATCH[2]}
@@ -104,6 +126,9 @@ if [ "${DISTRIBUTION}" == "Ubuntu" ] ; then
          NAME="${NAME}-LTS"
          RELEASE="${RELEASE} LTS"
       fi
+      if [ $y -lt 20 ] ; then
+         HTTP_DIRECTORY="${HTTP_DIRECTORY}-legacy"
+      fi
    else
       echo >&2 "ERROR: Invalid Ubuntu release ${RELEASE}!"
       exit 1
@@ -111,9 +136,29 @@ if [ "${DISTRIBUTION}" == "Ubuntu" ] ; then
 elif [ "${DISTRIBUTION}" == "Fedora" ] ; then
    BUILDER_INSTALL="fedora-${RELEASE}"
    NAME="${NAME}-Fedora-${RELEASE}"
+   HTTP_DIRECTORY="http/fedora"
+elif [ "${DISTRIBUTION}" == "FreeBSD" ] ; then
+   BUILDER_INSTALL="freebsd-${RELEASE}"
+   NAME="${NAME}-FreeBSD-${RELEASE}"
+   HTTP_DIRECTORY="http/freebsd"
+   if [[ "${RELEASE}" =~ ^([0-9]*).([0-9]*)$ ]] ; then
+      major=${BASH_REMATCH[1]}
+      minor=${BASH_REMATCH[2]}
+   else
+      echo >&2 "ERROR: Invalid FreeBSD release ${RELEASE}!"
+      exit 1
+   fi
 else
    echo >&2 "ERROR: Invalid distribution ${DISTRIBUTION}!"
    exit 1
+fi
+
+if [ "${HTTP_DIRECTORY}" != "http/ubuntu-legacy" ] ; then
+   if [ ${USE_SEPARATE_DISKS} -eq 0 ] ; then
+      HTTP_DIRECTORY="${HTTP_DIRECTORY}-1disk"
+   else
+      HTTP_DIRECTORY="${HTTP_DIRECTORY}-3disks"
+   fi
 fi
 
 
@@ -146,6 +191,7 @@ EOF
 (
    insert-json vmsetup/${BUILDER_VMSETUP}.json
    echo ","
+   echo "\"http_directory\": \"${HTTP_DIRECTORY}\","
    insert-json installer/${BUILDER_INSTALL}.json
 ) >>${JSONTMP}
 cat >>${JSONTMP} <<EOF
@@ -204,6 +250,7 @@ echo " - PROJECT=${PROJECT}"
 echo " - DISTRIBUTION=${DISTRIBUTION}"
 echo " - RELEASE=${RELEASE}"
 echo " - PROVISIONERS=${PROVISIONERS}"
+echo " - HTTP_DIRECTORY=${HTTP_DIRECTORY}"
 echo " - VM_DISK_ROOT=${VM_DISK_ROOT} (MiB)"
 if [ ${USE_SEPARATE_DISKS} -ne 0 ] ; then
    echo " - VM_DISK_HOME=${VM_DISK_HOME} (MiB)"
