Improved script.

diff --git a/evaluation/Run-Measurement8 b/evaluation/Run-Measurement8
--- a/evaluation/Run-Measurement8
+++ b/evaluation/Run-Measurement8
@@ -35,7 +35,7 @@
 
 DIRECTORY="Measurement8"
 INTERFACE="any"
-RUNTIME=10
+RUNTIME=60
 
 IP_ENODEB="10.1.1.87"
 IP_HSS="10.208.0.200"
@@ -53,7 +53,7 @@ PROMETHEUS_METRICS="osm_cpu_load_current osm_cpu_load_15min osm_cpu_load_1min os
 
 # ====== Initialise =========================================================
 if [ "${SUDO_UID}:${SUDO_GID}" == ":" ] ; then
-   echo >&2 "ERROR: Run this script with sudo, since it has to enable ECN and start tcpdump!"
+   echo >&2 "ERROR: Run this script with sudo, since it has to enable ECN and start tshark!"
    exit 1
 fi
 
@@ -106,7 +106,8 @@ SUMMARY_UPDATED="${DIRECTORY}/results.summary.updated"
 saturatedFlow="const0:const1400"
 streamingFlow="const60:const20000"   # 9.6 Mbit/s payload
 maxMsgSize=1400                      # Max. 1440 bytes per SCTP message/UDP packet
-tcpdumpSnaplens="128"   # "64 65536"
+tcpdumpSnaplens="128"   # "128 65536"
+remoteSnaplen="`echo ${tcpdumpSnaplens} | xargs -n1 | head -n1`"   # Just use the first one
 
 
 # ###### Start monitoring EPC component #####################################
@@ -126,10 +127,10 @@ start-monitoring ()
 
    ${ssh}${ip} /bin/bash -c "\"\\
 killall -q -sKILL sar ; \\
-sudo killall -q -sKILL tcpdump ; \\
-sudo rm -f /tmp/*.pcap /tmp/*.data /tmp/*.out /tmp/*.xz ; \\
-echo \\\"${Component}: starting tcpdump ...\\\" ; \\
-{ nohup sudo tcpdump -i any -n -s 128 -w /tmp/${id}-${component}.pcap '!(tcp port 22)' >/tmp/${id}-${component}-tcpdump.out 2>&1 & } ; \\
+sudo killall -q -sKILL tshark ; \\
+sudo rm -f /tmp/*.pcap* /tmp/*.data /tmp/*.out /tmp/*.xz ; \\
+echo \\\"${Component}: starting tshark ...\\\" ; \\
+{ nohup sudo tshark -i any -n -s ${remoteSnaplen} -w /tmp/${id}-${component}.pcap \'!(tcp port 22 or udp port 1194)\' >/tmp/${id}-${component}-tshark.out 2>&1 & } ; \\
 echo \\\"${Component}: starting sar ...\\\" ; \\
 { nohup sar -o /tmp/${id}-${component}.data ${sysstatParameters} >/tmp/${id}-${component}-sar.out 2>&1 & } ;\\
 echo \\\"${Component}: monitoring ready!\\\" ; \\
@@ -155,7 +156,7 @@ stop-monitoring ()
 
    ${ssh}${ip} /bin/bash -c "\"\\
 killall -q -sKILL sar ; \\
-sudo killall -q -sINT tcpdump ; \\
+sudo killall -q -sINT tshark ; \\
 sleep 5 ; \\
 find /tmp -maxdepth 1 -name ${id}-${component}.pcap | xargs -r sudo chown nornetpp:nornetpp ; \\
 find /tmp -maxdepth 1 -name ${id}-${component}.pcap | xargs -r xz -T0 ; \\
@@ -189,7 +190,7 @@ get-prometheus-metrics ()
 
 
 # ====== Run measurements ===================================================
-for qosBandwidth in 10000 ; do   # 100000
+for qosBandwidth in 100000 ; do   # 100000
    qosDelay=0
    qosLossRate=0.0
    qosErrorRate=0.0
@@ -244,10 +245,10 @@ for qosBandwidth in 10000 ; do   # 100000
          wait
 
 
-         # ====== Start tcpdump =============================================
-         echo "Starting tcpdump ..."
+         # ====== Start tshark =============================================
+         echo "Starting tshark ..."
          for tcpdumpSnaplen in ${tcpdumpSnaplens} ; do
-            tcpdump -i ${INTERFACE} -w "${prefix}-${tcpdumpSnaplen}.pcap" -s ${tcpdumpSnaplen} -n '!(tcp port 22)' &
+            tshark -i ${INTERFACE} -w "${prefix}-${tcpdumpSnaplen}.pcap" -s ${tcpdumpSnaplen} -n '!(tcp port 22 or udp port 1194)' &
          done
          sleep 3
          for tcpdumpSnaplen in ${tcpdumpSnaplens} ; do
@@ -283,8 +284,8 @@ for qosBandwidth in 10000 ; do   # 100000
          wait ${netPerfMeterPID}
          echo "OK!"
          endTime=`date +"%s"`
-         echo "Stopping tcpdump ..."
-         killall tcpdump || true
+         echo "Stopping tshark ..."
+         killall tshark || true
          wait
 
 
